/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.task2;
import java.io.File;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

public class App {
    public static void main(String[] args) {
        try {
            File inputFile = new File("data.xml");
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            Document doc = dBuilder.parse(inputFile);
            doc.getDocumentElement().normalize();
            NodeList nList = doc.getElementsByTagName("record");
            for (int temp = 0; temp < nList.getLength(); temp++) {
                Element record = (Element) nList.item(temp);
                String name = record.getElementsByTagName("name").item(0).getTextContent();
                String postalZip = record.getElementsByTagName("postalZip").item(0).getTextContent();
                String region = record.getElementsByTagName("region").item(0).getTextContent();
                String country = record.getElementsByTagName("country").item(0).getTextContent();
                String address = record.getElementsByTagName("address").item(0).getTextContent();
                String list = record.getElementsByTagName("list").item(0).getTextContent();
                System.out.println("Name: " + name);
                System.out.println("Postal ZIP code: " + postalZip);
                System.out.println("Region: " + region);
                System.out.println("Country: " + country);
                System.out.println("Address: " + address);
                System.out.println("List: " + list);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
