/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.task2;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

public class AppTest {
    
}
